AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

plugins:
  - rubocop-minitest

Layout/LineLength:
  Max: 200

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Relax some metrics for reasonable code
Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 35

# Allow development dependencies in gemspec for gems
Gemspec/DevelopmentDependencies:
  Enabled: false

Style/Documentation:
  Enabled: false

# Allow longer blocks for configuration and setup
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
    - "lib/fast_mcp_pubsub/railtie.rb"  # Debug logging temporarily increases block length
